### ISSUE TITLE
Run a Maintainer Activity Report for Besu Repositories.

### ISSUE THREAD

**Issue by shemnon** [hyperledger/governance#1]
Can I get a maintainer/contributor activity report for the besu repositories?  The one that lists last active dates.  From 22 Dec 2021 to present in case a time range is also needed.

Critical Repos - 
* https://github.com/hyperledger/besu
* https://github.com/hyperledger/besu-docs
* https://github.com/hyperledger/besu-native
* https://github.com/hyperledger/homebrew-besu

**Comment by ryjones** [comment]
@shemnon [how does this look?](https://github.com/ryjones/gal-besu/blob/main/extract.md)

the raw-ish data is in the repo.
