### ISSUE TITLE
Unarchive repo ursa-python and rename to indy-bls-wrapper-python

### ISSUE THREAD

**Issue by swcurran** [hyperledger/governance#102]
Please include:

* GitHub repo to create: rename and activate (change from archived) [ursa-python](https://github.com/hyperledger-archives/ursa-python) to indy-bls-wrapper-python
* Project to be added to: Hyperledger Indy
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger/teams))
	* Team name:
	* Role:
		- Read: 
		- Triage
		- Write
		- Manage: indy-vdr-maintainers
		- Admin: indy-admin

**Comment by ryjones** [comment]
[here you go](https://github.com/hyperledger/indy-bls-wrapper-python)!

**Comment by swcurran** [comment]
Thanks!
