### ISSUE TITLE
Create a repo: aries-bbs-rs

### ISSUE THREAD

**Issue by swcurran** [hyperledger/governance#103]
Please include:

* GitHub repo to create: aries-bbs-rs
* Project to be added to: Hyperledger Aries
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger/teams))
	* Team name: aries-bbs-maintainers
	* Members: @andrewwhitehead @blu3beri @TimoGlastra @mikelodder7 @WadeBarnes 
	* Role:
		- Read: usual read members (all of Aries)
		- Triage
		- Write
		- Manage
		- Admin aries-bbs-maintainers

**Comment by ryjones** [comment]
[here you go!](https://github.com/hyperledger/aries-bbs-rs)

**Comment by swcurran** [comment]
Thanks!

**Comment by ryjones** [comment]
@swcurran done and done!

**Comment by swcurran** [comment]
Thanks @ryjones !
