### ISSUE TITLE
Add Michael Timofeev, our QA, to GitHub

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/governance#104]
**GitHub ID to add**: https://github.com/timofeevmd

**Project to be added to**:

* https://github.com/hyperledger/iroha
* https://github.com/hyperledger/iroha-java
* https://github.com/hyperledger/iroha-python

**Teams to be added to**:

* https://github.com/orgs/hyperledger/teams/iroha-maintainers
* https://github.com/orgs/hyperledger/teams/iroha-python
* https://github.com/orgs/hyperledger/teams/iroha-java
* https://github.com/orgs/hyperledger/teams/iroha-javascript

**Comment by ryjones** [comment]
please update the maintainers.md as appropriate

**Comment by ryjones** [comment]
invites extended!
