### ISSUE TITLE
Add someone to GitHub org

### ISSUE THREAD

**Issue by swcurran** [hyperledger/governance#108]
If you want to be able to assign bugs to someone, they only need **Read** access.

Not sure what permission.  We need them to able to be assigned to issues at least. I think that is just READ, but not certain.

Please include:

* GitHub ID to add: usingtechnology, hiteshgh
* Project to be added to: Aries

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams):
* Role:
	- Read
	- Triage
	- Write
	- Manage
	- Admin

**Comment by swcurran** [comment]
Both are working for BC Gov on Aries related projects. @usingtechnology is likely to a maintainer for ACA-Py real soon now, while @hiteshgh is a scrum master and so is assigning tickets and updating their status (mostly in ZenHub though...).  Hope that helps.

**Comment by ryjones** [comment]
@swcurran I added them both to the https://github.com/orgs/hyperledger/teams/aries-triage team which has triage for all aries-* repos
