### ISSUE TITLE
Add Coveralls bot and Coveralls GitHub App to iroha repository

### ISSUE THREAD

**Issue by BAStos525** [hyperledger/governance#109]
If you want to be able to assign bugs to someone, they only need **Read** access.

Please include:

* GitHub ID to add: [coveralls](https://github.com/coveralls)
* Project to be added to: [iroha](https://github.com/hyperledger/iroha)

One of:

* Role:
	- Read

Add [Coveralls GitHub App](https://github.com/marketplace/coveralls) to hyperledger/iroha repo.

Useful links
- [iroha issue ##3542](https://github.com/hyperledger/iroha/issues/3542)

**Comment by ryjones** [comment]
OK, it is installed. [I think you need to install this action](https://github.com/marketplace/actions/coveralls-github-action) to make it work
