### ISSUE TITLE
Publishing to the Visual Studio Code Marketplace

### ISSUE THREAD

**Issue by aklenik** [hyperledger/governance#11]
The Caliper team would like to publish a VSCode extension soon as part of an ongoing mentorship project.

The publishing process [requires the following](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token):
1. Creating an organization in Azure DevOps (already exists probably)
2. Creating a personal access token 
3. Creating a publisher (the name will be included in the extension manifest)

We would also like to ask for some branding help (sorry, if this is not the appropriate forum for this):
* A **non-SVG** Caliper icon of 256x256 pixels as the extension's main icon
* A grayscale Caliper icon (the same size as above would probably be enough) for the [view container](https://code.visualstudio.com/api/extension-guides/tree-view#view-container) of the extension

Please include:
* GitHub repo: https://github.com/hyperledger/caliper
* Endpoint: N.A., performed by the official `vsce` tool

**Comment by ryjones** [comment]
@aklenik who should I invite to the ADO org? github alias?

**Comment by ryjones** [comment]
Logos:

![hyp-caliper-256-grey](https://user-images.githubusercontent.com/466142/182632746-347a0771-d1a1-4fcb-98f5-bba43e42e113.png)
![hyp-caliper-256](https://user-images.githubusercontent.com/466142/182632751-7b3c36a4-f4b9-496c-8486-d463ce2daf6d.png)

**Comment by aklenik** [comment]
> @aklenik who should I invite to the ADO org? github alias? Also, which repo?

@ryjones I don't know how the ADO process for this works, I thought that Hyperledger has a registered org, a general `hyperledger` publisher (that can also be reused by other projects in the future to show a unified Hyperledger brand), and you create an access token (naming it "Caliper") that will be set as a GitHub secret for the Caliper repository. And then we can access it from the CI pipeline, so no direct involvement with ADO is needed for the maintainers (although it will be useful for accessing the extension-related analytics data).

Regardless of the actual process, the information you asked for:
* Repository: https://github.com/hyperledger/caliper
* Maintainers to invite: [Dave Kelsey](https://github.com/davidkel) (@davidkel), [Attila Klenik](https://github.com/aklenik) (@aklenik)

  And thanks for the icons! 💯

**Comment by ryjones** [comment]
I've invited you both [to ADO](https://dev.azure.com/Hyperledger/Caliper%20VSCode). I'll work on the rest later today

**Comment by ryjones** [comment]
I've added both of you as admins to the project in ADO

**Comment by ryjones** [comment]
I've added the `VSCODE` token to this repo. [Here is the marketplace listing](https://marketplace.visualstudio.com/manage/publishers/hyperledgerfoundation)

**Comment by ryjones** [comment]
Hi, @aklenik and @davidkel . Could you create Marketplace accounts for yourself, and tell me the email addresses directly, so I can add you?
