### ISSUE TITLE
Add someone to GitHub -- Jsyro to aries-triage

### ISSUE THREAD

**Issue by swcurran** [hyperledger/governance#110]
If you want to be able to assign bugs to someone, they only need **Read** access.

Please include:

* GitHub ID to add: jsyro
* Project to be added to: [ACA-Py](https://github.com/hyperledger/aries-cloudagent-python)

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams): [aries-triage](https://github.com/orgs/hyperledger/teams/aries-triage)
* Role:
	- Read
	- **Triage**
	- Write
	- Manage
	- Admin

**Comment by ryjones** [comment]
Done!
