### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by petermetz** [hyperledger/governance#111]
I would like to have @adrianbatuto added to the org so that their PRs get permission to run the CI without explicit approval (as they are working on their first PR)

Thank you very much in advance!

* GitHub ID to add: adrianbatuto
* Project to be added to: Cacti

One of:

* [cacti-contributors-accenture](https://github.com/orgs/hyperledger/teams/cacti-contributors-accenture):

**Comment by ryjones** [comment]
invite sent!
