### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by denyeart** [hyperledger/governance#116]
Please add the following IBMers to Hyperledger org:

MayRosenbaum 
semil
arkadiPiven
HagarMeir

**Comment by ryjones** [comment]
@denyeart which groups?

**Comment by ryjones** [comment]
Invites sent!

**Comment by denyeart** [comment]
@ryjones I think they just need to be Hyperledger org members to be able to get issues assigned to them. I don't think we even have groups for core fabric contributors, do we?

**Comment by ryjones** [comment]
@denyeart sort of - [take a look](https://github.com/orgs/hyperledger/teams/fabric-contributors/teams)

**Comment by denyeart** [comment]
@ryjones Ok, but is the "fabric contributors" group actually granted privileges anywhere? Not that I'm aware of...

**Comment by ryjones** [comment]
no, but sub-teams are. Anyway, looks gtg
