### ISSUE TITLE
Add Nikita Strygin, our Rust developer

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/governance#118]
**GitHub ID to add**: @DCNick3

**Project to be added to**:

- [hyperledger/iroha](https://github.com/hyperledger/iroha)
- [hyperledger/iroha-java](https://github.com/hyperledger/iroha-java)
- [hyperledger/iroha-python](https://github.com/hyperledger/iroha-python)

**Teams to be added to**:

- [github.com/orgs/hyperledger/teams/iroha-maintainers](https://github.com/orgs/hyperledger/teams/iroha-maintainers)
- [github.com/orgs/hyperledger/teams/iroha-python](https://github.com/orgs/hyperledger/teams/iroha-python)
- [github.com/orgs/hyperledger/teams/iroha-java](https://github.com/orgs/hyperledger/teams/iroha-java)
- [github.com/orgs/hyperledger/teams/iroha-javascript](https://github.com/orgs/hyperledger/teams/iroha-javascript)

**Comment by ryjones** [comment]
Invite extended. Please update the MAINTAINERS.md file

**Comment by 6r1d** [comment]
Thanks, we will.
