### ISSUE TITLE
Transfer a repo

### ISSUE THREAD

**Issue by mepeltier** [hyperledger/governance#119]
This project has been discussed on the Aries WG and ACA-PUG meetings, and attendees were generally in agreement that this should be added to the Hyperledger Aries project. 

Please include:
* GitHub repo to transfer: https://github.com/Indicio-tech/aries-socketdock
* Project to be added to: Aries
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger/teams))
	* Team name: aries-admins
	    * Role:
		- Read
		- Triage
		- Write 
		- Manage
		- Admin
        * Team name: aries-framework-javascript-committers, aries-cloudagent-python-committers
	    * Role:
		- Read
		- Triage
		- Write
	* Team name: aries-contributers
	    * Role:
		- Read
		- Triage

cc: @TelegramSam @swcurran @TimoGlastra @dbluhm

**Comment by ryjones** [comment]
@mepeltier please transfer the repo to me, `ryjones`

**Comment by dbluhm** [comment]
Transfer initiated (had to do the repo transfer dance so it will be coming from my user)

**Comment by ryjones** [comment]
[Here you go!](https://github.com/hyperledger/aries-socketdock)
