### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by Baha-sk** [hyperledger/governance#12]
Please include:

* GitHub ID to add: https://github.com/mishasizov-SK
* Project to be added to: 

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams):
This is weird, I am not in any of these teams? Although I can be assigned issues in aries-framework-go and be set as a reviewer as well.

I would say he should be able to be assigned issues and be selected as a reviewer to PRs in this aries-framework-go and aries-framework-go-ext projects.

* Role:
	- Read
	- Triage

while we're at it, those who are actively working on these projects are:
@HeidiHan0000
@mishasizov-SK
@vkubiv
@DRK3
@Moopli
@fqutishat
@ashcherbakov
@Abdulbois 
@sudeshrshetty
@aholovko 
@troyronda
@bstasyszyn 
@talwinder50
@sandrask 
@rolsonquadras 
@Baha-sk 

you can remove the following from the teams as they are no longer part of our org:
@soluchok

**Comment by ryjones** [comment]
Please file a PR for [a-f-g-e](https://github.com/hyperledger/aries-framework-go-ext/blob/main/MAINTAINERS.md) and [a-f-g](https://github.com/hyperledger/aries-framework-go/blob/main/MAINTAINERS.md) referencing this issue. Once those are approved by the current people in the maintainer list and merged, I'll make the changes.

**Comment by Baha-sk** [comment]
We don't need the whole group to be maintainers, but we do need the list of users above to be able to triage and assign issues in the project.

**Comment by ryjones** [comment]
> We don't need the whole group to be maintainers, but we do need the list of users above to be able to triage and assign issues in the project.

You still need to file a PR :)

**Comment by ryjones** [comment]
@Baha-sk you're a member of https://github.com/orgs/hyperledger/teams/aries-contributors

**Comment by ryjones** [comment]
@Baha-sk I've invited everyone to a new triage group, which you maintain. You still need to update the maintainer files, tho.
