### ISSUE TITLE
Create a repo: anoncreds-revocation

### ISSUE THREAD

**Issue by swcurran** [hyperledger/governance#120]
Please include:

* GitHub repo to create: anoncreds-revocation
* Project to be added to: AnonCreds
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger/teams))
        * Same as for anoncreds-spec
	* Team name: 
	* Role:
		- Read
		- Triage
		- Write
		- Manage
		- Admin

Thanks!

**Comment by ryjones** [comment]
[enjoy](https://github.com/hyperledger/anoncreds-revocation)! Please create a MAINTAINERS.md file.
