### ISSUE TITLE
Add Orange Ng, our intern

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/governance#122]
**GitHub ID to add**: @OrangeNg

**Project to be added to**:

- https://github.com/hyperledger/iroha
- https://github.com/hyperledger/iroha-javascript
- https://github.com/hyperledger/iroha-java
- https://github.com/hyperledger/iroha-python

**Teams to be added to**:

- https://github.com/orgs/hyperledger/teams/iroha-maintainers
- https://github.com/orgs/hyperledger/teams/iroha-python
- https://github.com/orgs/hyperledger/teams/iroha-java
- https://github.com/orgs/hyperledger/teams/iroha-javascript

Context: [Hyperledger Wiki page](https://wiki.hyperledger.org/pages/viewpage.action?pageId=80778579), [LFX page](https://mentorship.lfx.linuxfoundation.org/project/8a6b5853-369c-48e6-9445-98520a8c28dc)

**Comment by SeanBohan** [comment]
Done
