### ISSUE TITLE
Add Yasser Arguelles Snape, our intern

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/governance#123]
**GitHub ID to add**: @RealNeGate

**Project to be added to**:

- https://github.com/hyperledger/iroha
- https://github.com/hyperledger/iroha-javascript
- https://github.com/hyperledger/iroha-java
- https://github.com/hyperledger/iroha-python

**Teams to be added to**:

- https://github.com/orgs/hyperledger/teams/iroha-maintainers
- https://github.com/orgs/hyperledger/teams/iroha-python
- https://github.com/orgs/hyperledger/teams/iroha-java
- https://github.com/orgs/hyperledger/teams/iroha-javascript

Context: [Hyperledger Wiki page](https://wiki.hyperledger.org/display/INTERN/Iroha+2%3A+DSL), [LFX page](https://mentorship.lfx.linuxfoundation.org/project/cda1496b-0c36-4c1b-98b5-dee5d95f494a)

**Comment by SeanBohan** [comment]
Done
