### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by AkankshaAI** [hyperledger/governance#124]
Request to @ryjones by Akanksha Rani , LFX mentee'23 Hyperledger Onboarding 

* GitHub ID to add: AkankshaAI
* Project to be added to: Hyperledger tooling
Please add me in : https://github.com/hyperledger-tooling

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams):
* https://github.com/hyperledger-tooling
* Role:
	- Read
	- Triage
	- Write

**Comment by ryjones** [comment]
Invite sent!
