### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/governance#126]
If you want to be able to assign bugs to someone, they only need **Read** access.

Please include:

* GitHub ID to add: mepeltier
* Project to be added to: aries-socketdock

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams): I think it makes sense to create a new team for aries-socketdock-committers under the aries-contributors team
* Role: Manage

**Comment by ryjones** [comment]
Invite sent!
