### ISSUE TITLE
Change repo ACL

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/governance#127]
* Repo to change access: aries-socketdock
* GitHub ID to add: frostyfrog

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams): I think a new team makes sense; aries-socketdock-committers under the aries-contributors team (also mentioned in #126)
* Role: Manage

**Comment by ryjones** [comment]
Invite sent, ACL sent
