### ISSUE TITLE
Change repo ACL for Harmonia

### ISSUE THREAD

**Issue by gendal** [hyperledger/governance#128]
* Repo to change access: https://github.com/hyperledger-labs/harmonia
* GitHub ID to add: fowlerrr and ILoomans

Hi there - I'm not exactly sure which permission we need but could you give the two IDs above the ability to write to the Harmonia repo please? That is: we need them to be able to create/push to new branches, etc., from which they can then raise PRs for merging to main.  Many thanks - Richard.

**Comment by SeanBohan** [comment]
Both added. They need to accept the invite.

**Comment by gendal** [comment]
Thank you!
