### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by siladu** [hyperledger/governance#129]
If you want to be able to assign bugs to someone, they only need **Read** access.

Please include:

* GitHub ID to add: @naviechan
* Project to be added to: Besu

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams):
https://github.com/orgs/hyperledger/teams/besu-triage

**Comment by ryjones** [comment]
Invitation sent!
