### ISSUE TITLE
Add anna-jackson to GitHub

### ISSUE THREAD

**Issue by nguyer** [hyperledger/governance#13]
Please include:

* GitHub ID to add: anna-jackson
* Project to be added to: FireFly
* Team to be added to: https://github.com/orgs/hyperledger/teams/firefly-committers

**Comment by ryjones** [comment]
Invite sent!

**Comment by nguyer** [comment]
Hi @ryjones sorry to bother you again on this one. @anna-jackson was actually on vacation when she received the invite, so it had expired by the time she tried to accept it. Is it possible to re-send the invite? Thanks!
