### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by xiaor2** [hyperledger/governance#130]
If you want to be able to assign bugs to someone, they only need **Read** access.

Please include:

* GitHub ID to add: xiaor2
* Project to be added to: Hyperledger Cello

One of: Linux Foundation Mentorship Program Intern

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams):
* Role:
	- Read
	- Triage
	- Write
	- Manage
	- Admin

**Comment by ryjones** [comment]
@hyperledger/cello-maintainers

**Comment by ryjones** [comment]
@hyperledger/cello-maintainers please approve

**Comment by ryjones** [comment]
@xiaor2 invite sent!
