### ISSUE TITLE
Add PyPI publishing token

### ISSUE THREAD

**Issue by andrewwhitehead** [hyperledger/governance#132]
Repo: https://github.com/hyperledger/indy-bls-wrapper-python

Package name: `indy_bls` (not previously published)

The repo does currently have a `PYPI_PASSWORD` token, but it is project-scoped to the old package name.

**Comment by ryjones** [comment]
Updated, published https://pypi.org/project/indy-bls/#description

**Comment by andrewwhitehead** [comment]
Thank you!
