### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by YUNGU23** [hyperledger/governance#133]
If you want to be able to assign bugs to someone, they only need **Read** access.

Please include:

* GitHub ID to add: YUNGU23
* Project to be added to: Cello

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams):
* Role:
	- Read
	- Triage
	- Write
	- Manage
	- Admin

**Comment by ryjones** [comment]
Invite sent!
