### ISSUE TITLE
Add Bogdan Yamkovoy (our technical writer) to GitHub

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/governance#135]
**GitHub ID to add:** @yamkovoy

**Project to be added to:**

* https://github.com/hyperledger/iroha-2-docs
* https://github.com/hyperledger/iroha
* https://github.com/hyperledger/iroha-java
* https://github.com/hyperledger/iroha-python

**Teams to be added to:** [`iroha-maintainers`](https://github.com/orgs/hyperledger/teams/iroha-maintainers)

**Role:** Read / Write

**Comment by ryjones** [comment]
Invited! Please update the MAINTAINERS.md files.

**Comment by 6r1d** [comment]
Thanks, we will.
