### ISSUE TITLE
Add johnhomantaring, zondervancalvez, micoferdinand98, ruzell22, aldousalvarez to the GitHub Org

### ISSUE THREAD

**Issue by petermetz** [hyperledger/governance#138]
If you want to be able to assign bugs to someone, they only need **Read** access.

Please include:

* GitHub IDs to add:
   - johnhomantaring
   - zondervancalvez
   - micoferdinand98
   - ruzell22
   - aldousalvarez
* Project to be added to: Cacti

One of:

* Team to be added to
  - https://github.com/orgs/hyperledger/teams/cacti-contributors-accenture/members
* Role:
	- Read
	- Triage

**Comment by ryjones** [comment]
Hi, @petermetz . I've sent the invites; I also [changed the repo permissions](https://github.com/orgs/hyperledger/teams/cacti-contributors-accenture/repositories) to Triage for the Accenture team. I assume you can add members in this team to appropriate teams if they need write access.

**Comment by petermetz** [comment]
> Hi, @petermetz . I've sent the invites; I also [changed the repo permissions](https://github.com/orgs/hyperledger/teams/cacti-contributors-accenture/repositories) to Triage for the Accenture team. I assume you can add members in this team to appropriate teams if they need write access.

@ryjones Thank you very much! Yes, I can add them to the team once they are in the org! Cheers!
