### ISSUE TITLE
Create a repo: iroha-2-examples

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/governance#139]
* GitHub repo to create: `iroha-2-examples`
* Project to be added to:  https://github.com/hyperledger/iroha
* Teams with which access:
	* Team name: [`iroha-maintainers`](https://github.com/orgs/hyperledger/teams/iroha-maintainers)
	* Role:
		- Read
		- Triage (not sure)
		- Write
		- Manage

**Comment by ryjones** [comment]
[here you go!](https://github.com/hyperledger/iroha-2-examples)
