### ISSUE TITLE
Add Dzianis Andreyenka to GitHub

### ISSUE THREAD

**Issue by nguyer** [hyperledger/governance#140]
Hi there,

The FireFly maintainers voted to add Dzianis Andreyenka as a maintainer and codeowner of the new FireFly Tezos blockchain connector. This is a request to add Dzianis Andreyenka to the Hyperledger Org and the corresponding team. Thanks!

* GitHub ID to add: [denisandreenko](https://github.com/denisandreenko)
* Project to be added to: Hyperledger FireFly
* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams): https://github.com/orgs/hyperledger/teams/firefly-tezosconnect-maintainers

**Comment by ryjones** [comment]
Invite sent!
