### ISSUE TITLE
Add Bogdan Yamkovoy to GitHub

### ISSUE THREAD

**Issue by yamkovoy** [hyperledger/governance#143]
**GitHub ID to add**: @yamkovoy

**Projects to be added to**:

* https://github.com/hyperledger/iroha-2-docs
* https://github.com/hyperledger/iroha
* https://github.com/hyperledger/iroha-java
* https://github.com/hyperledger/iroha-python

**Teams to be added to**: [`iroha-maintainers`](https://github.com/orgs/hyperledger/teams/iroha-maintainers)

> Has been added to the `MAINTAINERS.md` file as part of the [PR #388](https://github.com/hyperledger/iroha-2-docs/pull/388) (`hyperledger/iroha-2-docs` repo).

**Role**: Read / Write

**Note**: This request was approved before (see issue #135), but is created again since I had to restore access to my account, and GitHub has removed me from all of the teams I had been a part of.

**Comment by SeanBohan** [comment]
Invite sent

**Comment by SeanBohan** [comment]
Done
