### ISSUE TITLE
Change repo ACL

### ISSUE THREAD

**Issue by jleach** [hyperledger/governance#144]
* Repo to change access:

https://github.com/hyperledger/aries-mediator-service

* GitHub ID to add: 

- [ ] dbluhm
- [ ] jamshale
- [ ] jsyro
- [ ] WadeBarnes

Remove:

- [ ] ianco
- [ ] jleach

One of:

* [aries-mediator-service-committers](https://github.com/orgs/hyperledger/teams/aries-mediator-service-committers):
* Role: 
	- Manage / Maintain

**Comment by ryjones** [comment]
Done!
