### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by karimStekelenburg** [hyperledger/governance#147]
I would like user @2mau to be able to manage (read, write, delete) this [project board](https://github.com/orgs/hyperledger/projects/32). I'm not sure what the correct team and scope is for this.

* GitHub ID to add: @2mau
* Project to be added to: Aries

* Team to be added to https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors

**Comment by ryjones** [comment]
invites sent!
