### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/governance#15]
Please include:

* GitHub ID to add: @genaris
* Project to be added to: Aries Framework JavaScript

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams):  https://github.com/orgs/hyperledger/teams/aries-framework-javascript-committers

We would like to add @genaris as a maintainer to the Aries Framework JavaScript project. He has been active participant in the community and contributor to the framework for a considerable amount of time.

**Comment by ryjones** [comment]
Invite sent! Please update your maintainers.md file as well.
