### ISSUE TITLE
Create a repo besu-verkle-trie

### ISSUE THREAD

**Issue by matkt** [hyperledger/governance#152]
Please include:

* GitHub repo to create:

[https://github.com/hyperledger/besu-verkle-trie](https://github.com/hyperledger/besu-verkle-trie)

* Project to be added to: besu project

* Teams with which access: 

@hyperledger/besu-admin (admin)
[Besu Admin](https://github.com/orgs/hyperledger/teams/besu-admin)

@hyperledger/besu-contributors (triage)
[Besu Contributors](https://github.com/orgs/hyperledger/teams/besu-contributors)

@hyperledger/besu-maintainers (maintain)
[Besu Maintainers](https://github.com/orgs/hyperledger/teams/besu-maintainers)

@hyperledger/besu-triage (write)
[Besu Triage](https://github.com/orgs/hyperledger/teams/besu-triage)

**Comment by ryjones** [comment]
[here you go!](https://github.com/hyperledger/besu-verkle-trie)
