### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger/governance#154]
Please include:

* GitHub ID to add: [munapower](https://github.com/munapower)
* Project to be added to: [fabric-private-chaincode](https://github.com/hyperledger/fabric-private-chaincode)

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams): https://github.com/orgs/hyperledger/teams/fabric-private-chaincode-committers
* Role:
	- Maintainer

**Comment by ryjones** [comment]
Invite sent!
