### ISSUE TITLE
Add Vladislav Amuzinski (our Rust developer) to GitHub

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/governance#155]
**GitHub ID to add:** @VAmuzing

**Project to be added to:**

* https://github.com/hyperledger/iroha
* https://github.com/hyperledger/iroha-java
* https://github.com/hyperledger/iroha-javascript
* https://github.com/hyperledger/iroha-python
* https://github.com/hyperledger/iroha-2-docs
* https://github.com/hyperledger/iroha-rfcs
* https://github.com/hyperledger/iroha-2-examples

**Teams to be added to:**

* [`iroha-maintainers`](https://github.com/orgs/hyperledger/teams/iroha-maintainers)
* [`iroha-rfc-maintainers`](https://github.com/orgs/hyperledger/teams/iroha-rfc-maintainers)
* [`iroha-python`](https://github.com/orgs/hyperledger/teams/iroha-python)
* [`iroha-java`](https://github.com/orgs/hyperledger/teams/iroha-java)
* [`iroha-javascript`](https://github.com/orgs/hyperledger/teams/iroha-javascript)

**Role:** Read / Write

**Comment by ryjones** [comment]
Invites sent!
