### ISSUE TITLE
Add someone to GitHub -  Marina Gómez Cepeda 

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/governance#159]
If you want to be able to assign bugs to someone, they only need **Read** access.

Please include:

* GitHub ID to add: mgCepeda 
* Project to be added to: bevel and bevel-samples

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams): Bevel Contributors
* Role:
	- Read
	- Triage
	- Write

**Comment by ryjones** [comment]
invite sent!
