### ISSUE TITLE
Please add our new QA to the Hyperledger GitHub org

### ISSUE THREAD

**Issue by dmitrivenger** [hyperledger/governance#16]
Please include:

* GitHub ID to add: astrokov7
* Project to be added to: Iroha 2

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams):
* Role:
	- Read
	- Triage
	- Write
	- Manage
	- Admin

**Comment by ryjones** [comment]
Invite sent! @astrokov7 visit [this page](https://github.com/hyperledger) to accept
