### ISSUE TITLE
Create a repo: `solang-aqd`

### ISSUE THREAD

**Issue by xermicus** [hyperledger/governance#168]
I've got a request for a new repository: `solang-aqd` will be the home for our tooling (node interactions with the blockchains we support). We decided that it's best to keep the tooling separate from the compiler.

* GitHub repo to create: `solang-aqd`
* Project to be added to: Solang
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger/teams))
	* Team name: [solang-committers](https://github.com/orgs/hyperledger/teams/solang-committers)
	* Role:
		- Admin

**Comment by ryjones** [comment]
[Here you go!](https://github.com/hyperledger/solang-aqd)
