### ISSUE TITLE
Add someone to GitHub: xprazak2

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/governance#174]
* GitHub ID to add: https://github.com/xprazak2/
* Project to be added to: https://github.com/hyperledger/aries-vcx

One of:
* Team to be added to: https://github.com/orgs/hyperledger/teams/aries-vcx-contributors

**Comment by ryjones** [comment]
Done. [Please update your maintainers file](https://github.com/hyperledger/aries-vcx/blob/main/MAINTAINERS.md) as it looks very out-of-date.
