### ISSUE TITLE
Create a repo: iroha-news

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/governance#175]
Please include:

* GitHub repo to create: [`iroha-news`](https://github.com/hyperledger/iroha-news)
* Project to be added to: Iroha
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger/teams))
	* Team name: [`iroha-maintainers`](https://github.com/orgs/hyperledger/teams/iroha-maintainers)
	* Role:
		- Admin

**Comment by ryjones** [comment]
[here you go!](https://github.com/hyperledger/iroha-news)
