### ISSUE TITLE
Create a repo: aries-uniffi-wrappers

### ISSUE THREAD

**Issue by conanoc** [hyperledger/governance#176]
* GitHub repo to create: aries-uniffi-wrappers
* Project to be added to: Aries
* Teams with which access: 
	* Team name: none

### Purpose of the repo

This repo is for the wrappers of the following components:
- Aries Askar: https://github.com/hyperledger/aries-askar
- AnonCreds Rust - https://github.com/hyperledger/anoncreds-rs
- Indy VDR: https://github.com/hyperledger/indy-vdr

This repo will contain three uniffi rust modules to create Swift and Kotlin wrappers of the above components.

**Comment by ryjones** [comment]
[here you go!](https://github.com/hyperledger/aries-uniffi-wrappers)

**Comment by conanoc** [comment]
Thanks. But, I need permission for the repo.

**Comment by ryjones** [comment]
@conanoc which teams need access, and who should be on those teams?

**Comment by conanoc** [comment]
@ryjones No teams. Just me.

**Comment by conanoc** [comment]
Now I have permission. Thanks.
