### ISSUE TITLE
Add @outSH to GitHub

### ISSUE THREAD

**Issue by petermetz** [hyperledger/governance#177]
@outSH has joined the Cacti maintainers!

Please include:

* GitHub ID to add: `outSH`
* Project to be added to: Cacti

One of:

* Team1: https://github.com/orgs/hyperledger/teams/cacti-maintainers
* Team2: https://github.com/orgs/hyperledger/teams/cacti-security-administration
* Role:
	- Admin

**Comment by ryjones** [comment]
done!
