### ISSUE TITLE
Transfer a repo

### ISSUE THREAD

**Issue by reflectivedevelopment** [hyperledger/governance#180]
As discussed in Aries Working Group Call. Attendees were generally in agreement that this should be added to the Hyperledger Aries project.

* GitHub repo to transfer: https://github.com/Indicio-tech/aries-akrida
* Project to be added to: Aries
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger/teams))
    Team name: aries-admins
        Role:
        Read
        Triage
        Write
        Manage
        Admin
    Team name: aries-framework-javascript-committers, aries-cloudagent-python-committers, aries-mediator-service-committers
        Role:
        Read
        Triage
        Write
    Team name: aries-contributers
        Role:
        Read
        Triage

**Comment by ryjones** [comment]
@reflectivedevelopment please transfer the repo to me, `ryjones`

**Comment by reflectivedevelopment** [comment]
frostyfrog  is doing the transfer as I already have a fork and github is being difficult.

**Comment by ryjones** [comment]
[here you go!](https://github.com/hyperledger/aries-akrida)
