### ISSUE TITLE
Transfer a repo -- the currently archived "ursa-docs" repo from hyperledger-archives

### ISSUE THREAD

**Issue by swcurran** [hyperledger/governance#181]
Hi -- Since the repository https://github.com/hyperledger-archives/ursa-docs contains only AnonCreds specifications, I'd like the repository unarchived and renamed to "anoncreds-tex".  From there, we can make other changes -- at least update the documents and add a Maintainers file, and make some updates to the document. We might move the two AnonCreds v1 documents (and build script) to the anoncreds-spec repo, including the full history of the file (which admittedly is pretty short).

Doable?

Please include:

* GitHub repo to transfer: https://github.com/hyperledger-archives/ursa-docs renamed to "anoncreds-tex"
* Project to be added to: AnonCreds
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger/teams))
	* Team name: AnonCreds Maintainers
	* Role:
		- Read
		- Triage
		- Write
		- Manage
		- Admin

**Comment by ryjones** [comment]
[here you go!](https://github.com/hyperledger/anoncreds-tex)
