### ISSUE TITLE
I am a Mentor at Learning Tokens, and would like to get access to our Hyperledger Lab Learning Tokens

### ISSUE THREAD

**Issue by AlfonsoGovela** [hyperledger/governance#186]
* Repo to change access:
* GitHub ID to add: 

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams):
* Role:
	- Read
	- Triage
	- Write
	- Manage
	- Admin

**Comment by AlfonsoGovela** [comment]
I am a Mentor at Learning Tokens, Hyperledger Mentorship Program 2023. Would like to have access to our Hyperledger Lab Learning Tokens

**Comment by ryjones** [comment]
Invite sent!
