### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by reflectivedevelopment** [hyperledger/governance#187]
If you want to be able to assign bugs to someone, they only need **Read** access.

Please include:

* GitHub ID to add: anwalker293
* Project to be added to: https://github.com/hyperledger/aries-akrida/

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams):
[aries-mediator-service-committers](https://github.com/orgs/hyperledger/teams/aries-mediator-service-committers)

**Comment by ryjones** [comment]
Invite sent!
