### ISSUE TITLE
Create a repo: Indy-besu

### ISSUE THREAD

**Issue by ashcherbakov** [hyperledger/governance#191]
Please include:

* GitHub repo to create: indy-besu
* Project to be added to: Hyperledger Indy 
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger/teams))
	* Team name: https://github.com/orgs/hyperledger/teams/indy-common/
	    * Role: Write
	* Team name: https://github.com/orgs/hyperledger/teams/indy-common/indy-besu-maintainers (New Team)
	    * Role: Manage/Admin
	    * Members: [Toktar](https://github.com/Toktar), [Artemkaaas](https://github.com/Artemkaaas),  [ashcherbakov](https://github.com/ashcherbakov).

**Comment by ryjones** [comment]
[Done. Please create a MAINTAINERS.md](https://github.com/hyperledger/indy-besu)
