### ISSUE TITLE
Add Shunkichi Sato, our Rust developer

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/governance#193]
If you want to be able to assign bugs to someone, they only need **Read** access.

* GitHub ID to add: @s8sato

**Project to be added to**:

- https://github.com/hyperledger/iroha
- https://github.com/hyperledger/iroha-javascript
- https://github.com/hyperledger/iroha-java
- https://github.com/hyperledger/iroha-python

**Teams to be added to**:

- https://github.com/orgs/hyperledger/teams/iroha-maintainers
- https://github.com/orgs/hyperledger/teams/iroha-python
- https://github.com/orgs/hyperledger/teams/iroha-java
- https://github.com/orgs/hyperledger/teams/iroha-javascript

**Role**: Write

Context: Sato-san has returned to our team. The `MAINTAINERS.md` file will be updated in https://github.com/hyperledger/iroha/pull/4254

**Comment by ryjones** [comment]
Done. I will note this is something you were able to do yourself, as s8sato was still a member of the Hyperledger org.
