### ISSUE TITLE
Change repo ACL: Add Tarek Elsayed to Solang Aqd

### ISSUE THREAD

**Issue by tareknaser** [hyperledger/governance#194]
* Repo to change access: https://github.com/hyperledger/solang-aqd
* GitHub ID to add: https://github.com/tareknaser

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams):
* Role: Write

I implemented Solang Aqd during my Hyperledger mentorship and I'm interested in becoming a maintainer for the project.

**Comment by ryjones** [comment]
@hyperledger/solang-committers thoughts?

**Comment by seanyoung** [comment]
Sounds good to me :)

**Comment by ryjones** [comment]
invites sent!

**Comment by xermicus** [comment]
@ryjones This is Tareks mentorship project. I'm very happy about his committed! Thanks for the approval.
