### ISSUE TITLE
Add Rafael Belchior and André Augusto to GitHub

### ISSUE THREAD

**Issue by petermetz** [hyperledger/governance#198]
**For now I'm just requesting to add Rafael and Andre to the GitHub org with read permissions to Cacti**

We are in talks about making Rafael a maintainer and I'm hoping that in a couple of days that gets confirmed as well and then we can add him to the maintainer group of Cacti as well, but for now, that's not a decision that's been finalized.

GitHub IDs:
https://github.com/RafaelAPB
https://github.com/AndreAugusto11

**Comment by ryjones** [comment]
Invites sent! I put them in [contributors](https://github.com/orgs/hyperledger/teams/cacti-contributors/members) which has no superpowers

**Comment by petermetz** [comment]
> Invites sent! I put them in [contributors](https://github.com/orgs/hyperledger/teams/cacti-contributors/members) which has no superpowers

@ryjones Thank you very much!
