### ISSUE TITLE
Create a repo

### ISSUE THREAD

**Issue by ale-linux** [hyperledger/governance#203]
Please include:

* GitHub repo to create: https://github.com/hyperledger/aries-bbs-go
* Project to be added to:  aries
* Teams with which access:
	* Team name: aries-bbs-maintainers
	* Role:
		- Admin
	* Team name: fabric-maintainers
	* Role:
		- Write

As per discussions here: https://github.com/hyperledger/aries-framework-go/issues/3633

Please add the following maintainers:
 - everyone in aries-bbs-maintainers
 - @ale-linux 
 - @sudeshrshetty
 - @troyronda
 - @fqutishat

**Comment by ryjones** [comment]
@ale-linux could you clarify the maintainer list? the accounts you list, should be added to the aries-bbs-maintainers team, or a new team?

**Comment by ale-linux** [comment]
@ryjones sorry for the confusion. The initial maintainers should be everyone in the aries-bbs-maintainers team plus the current aries-framework-go maintainers (@sudeshrshetty, @troyronda and @fqutishat) and myself (@ale-linux). I guess it's okay to add to aries-bbs-maintainers all of those who are not yet members of that team and then have the team be the initial maintainers.

**Comment by ryjones** [comment]
@ale-linux [OK take a look at the teams here](https://github.com/hyperledger/aries-bbs-go/settings/access) - if correct, please close this issue

**Comment by ale-linux** [comment]
Perfect, many thanks @ryjones! :+1:

**Comment by ale-linux** [comment]
@swcurran , speaking of which: what happened to the rust implementation of BBS+? The repo that contained it was also end-of-lifed afaik

**Comment by swcurran** [comment]
That was moved from Ursa to here: https://github.com/hyperledger/aries-bbssignatures-rs

**Comment by ale-linux** [comment]
@ryjones : I keep trying to add @yacovm to https://github.com/orgs/hyperledger/teams/aries-bbs-go-maintainers. He gets added okay but then after a while he keeps being autoremoved. Do you know why?

**Comment by ryjones** [comment]
@ale-linux you need to do a PR [here](https://github.com/hyperledger/governance/blob/fbf9cf0c265318a07b2f895d0b495cbdf8b2cc3e/access-control.yaml#L102)

**Comment by ryjones** [comment]
@ale-linux https://clowarden.io/audit/?time_range=3d&organization=hyperledger&page=1
