### ISSUE TITLE
Add @rwat17 to GitHub Org

### ISSUE THREAD

**Issue by petermetz** [hyperledger/governance#226]
* GitHub ID to add: rwat17
* Project to be added to: Cacti

One of:

* Role: https://github.com/orgs/hyperledger/teams/cacti-contributors
	- Triage

More context: I need Tomasz to have permission to click the little refresh icon that re-runs **a single job** of a GitHub workflow as documented in this guide:
https://github.com/hyperledger/cacti/blob/4a9fed35baefeac0ce53fc437820b6c33d2b66f2/FAQ.md#how-do-i-re-run-a-single-job-in-the-ci-through-the-github-ui

I'm hoping that the `triage` permission will get this done but we are in the experimentation phase to find out. 

cc: @rwat17

**Comment by ryjones** [comment]
@petermetz in the future, you can file a PR like #227

**Comment by rwat17** [comment]
I am not sure if I can comment on this. If not correct me please :)
@petermetz I have accepted the invitation but re-run icon is still not available.

**Comment by ryjones** [comment]
@rwat17 which PR?

**Comment by ryjones** [comment]
@rwat17 I hear you :) You might need to be a maintainer for that.
