### ISSUE TITLE
Change repo ACL

### ISSUE THREAD

**Issue by NickSneo** [hyperledger/governance#232]
* Repo to change access: web3j-* [(All web3j repos)](https://github.com/orgs/hyperledger/repositories?language=&q=web3j&sort=&type=all)
* GitHub ID to add:  [NickSneo](https://github.com/NickSneo), [gtebrean](https://github.com/gtebrean)

* Role:
	-
	- Manage
	- Write
	- Admin

**Comment by ryjones** [comment]
resolved
