### ISSUE TITLE
Add jt-nti in the right places

### ISSUE THREAD

**Issue by ryjones** [hyperledger/governance#238]
[@jt-nti needs](https://github.com/hyperledger/fabric-protos/pull/215#issuecomment-2050558124) access restored. However, he is only listed as emeritus maintainer in Fabric repos (which is why I removed him). @denyeart please [file a PR](https://github.com/hyperledger/governance/blob/main/access-control.yaml) and add him in the proper maintainer files

**Comment by denyeart** [comment]
I don't think James is a maintainer of any hyperledger repositories anymore (beyond some hyperledger-labs), but he remains a trusted advisor for several repositories.

It looks like who can approve is an org setting:

https://github.com/hyperledger/fabric-protos/settings/code_review_limits
✓ Limit to users explicitly granted read or higher access

Note that only @hyperledger/fabric-core-maintainers members can merge in this repository based on CODEOWNERS, but it would still be nice to allow others to indicate approval.

I see a team called read-only with 314 members.  Is the read-only team all members of the Hyperledger organization? What is the criteria for adding people to each? I know to assign issues to people they must be a member of Hyperledger organization. For example I should be able to assign an issue to James even though he is not a maintainer. So I think we'd want to be liberal about Hyperledger org membership. Are you removing all non-maintainers from these lists?

**Comment by ryjones** [comment]
yes, the `read-only` team is all members. I suggest making a `fabric-triage` team, or similar, and adding yourself as a maintainer and James (and other trusted people) to that team, as well as `read-only`.

We used to be very liberal with org membership, but it has caused us a problem in the past. That's why `read-only` exists. There will be a future complication which I can't discuss yet which means I need to keep the list pruned to trusted, active people.

**Comment by denyeart** [comment]
@ryjones Good idea. In fact we already had a fabric-triage team.

https://github.com/hyperledger/governance/pull/239
