### ISSUE TITLE
Transfer a repo

### ISSUE THREAD

**Issue by essbante-io** [hyperledger/governance#244]
Please include:

* GitHub repo to transfer: https://github.com/essbante-io/identus/
* Project to be added to: identus
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger/teams))
	* Team name: identus-maintainers
	* Role:
		- Read
		- Triage
		- Write
		- Manage
		- Admin

**Comment by essbante-io** [comment]
@ryjones as discussed on discord:

> we can rename the current repo to identus-cloud-agent, and create a new repo for Identus, if you have content for it
> 
> https://github.com/essbante-io/identus is the content for the landing repo, it is new and it only contains the required .md files

**Comment by ryjones** [comment]
repo transferred!
