### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/governance#251]
Please include:

* GitHub ID to add: saurabhkumarkardam, saikumarbommakanti 
* Project to be added to: Hyperledger Bevel

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams): https://github.com/orgs/hyperledger/teams/bevel-contributors
* Role: Same as https://github.com/orgs/hyperledger/teams/bevel-committers
	- Read
	- Triage

**Comment by ryjones** [comment]
Hi @suvajit-sarkar , please add them to https://github.com/hyperledger/bevel/blob/main/MAINTAINERS.md

**Comment by suvajit-sarkar** [comment]
Hi @ryjones, these guys are not maintainers, but would like them to have permission to create issues and move issues in project boards.
