### ISSUE TITLE
Transfer a repo

### ISSUE THREAD

**Issue by essbante-io** [hyperledger/governance#255]
Please include:

* GitHub repo to transfer: 
  - [https://github.com/input-output-hk/identus-mediator](https://github.com/input-output-hk/atala-prism-mediator)
  - [https://github.com/input-output-hk/identus-edge-agent-sdk-ts](https://github.com/input-output-hk/atala-prism-wallet-sdk-ts)
  - [https://github.com/input-output-hk/identus-edge-agent-sdk-kmp](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm)
  - [https://github.com/input-output-hk/identus-edge-agent-sdk-swift](https://github.com/input-output-hk/atala-prism-wallet-sdk-swift)
  - [https://github.com/input-output-hk/identus-apollo](https://github.com/input-output-hk/atala-prism-apollo/)
  - [https://github.com/input-output-hk/identus-docs](https://github.com/input-output-hk/atala-prism-docs)
  
* Project to be added to: identus
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger/teams))
	* Team name: identus-maintainers
	* Role:
		- Read
		- Triage
		- Write
		- Manage
		- Admin

**Comment by essbante-io** [comment]
@ryjones I will let you know about the transfer's schedule

**Comment by ryjones** [comment]
@essbante-io thank you

**Comment by essbante-io** [comment]
Pairs of repo mappings

https://github.com/input-output-hk/atala-prism-mediator 
https://github.com/input-output-hk/identus-mediator

https://github.com/input-output-hk/atala-prism-wallet-sdk-ts 
https://github.com/input-output-hk/identus-edge-agent-sdk-ts

https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm 
https://github.com/input-output-hk/identus-edge-agent-sdk-kmp

https://github.com/input-output-hk/atala-prism-wallet-sdk-swift 
https://github.com/input-output-hk/identus-edge-agent-sdk-swift

https://github.com/input-output-hk/atala-prism-apollo 
https://github.com/input-output-hk/identus-apollo

https://github.com/input-output-hk/atala-prism-docs 
https://github.com/input-output-hk/identus-docs
