### ISSUE TITLE
Create a repo agora-allosaurus-rs

### ISSUE THREAD

**Issue by mikelodder7** [hyperledger/governance#284]
Please include:

Please create under hyperledger-labs

agora-allosaurus-rs

It will just be me as a maintainer for now. I'll need all permissions associated with that role.

**Comment by ryjones** [comment]
[In the future, you can create a PR here](https://github.com/hyperledger-labs/governance/pull/75)

**Comment by mikelodder7** [comment]
Sure can do. I just used https://github.com/hyperledger/governance/issues/new/choose like before.

**Comment by ryjones** [comment]
[here you go](https://github.com/hyperledger-labs/agora-allosaurus-rs)!
