### ISSUE TITLE
Change GHCR contiainer image package ACL - Cacti - 

### ISSUE THREAD

**Issue by petermetz** [hyperledger/governance#299]
The container image in question: 
https://github.com/hyperledger/cacti/pkgs/container/cactus-corda-4-8-all-in-one-flowdb

I couldn't figure out what to change in the access-control.yaml to make this work, apologies for requiring the manual labor on your part!

I somehow lost (or never had?) access to one our Cacti container images on GHCR. 
Lost access = I can pull the image but cannot push. Also don't have access to its "Package Settings" page where I could change permissions on it.

Screenshot one shows how all other images we have looks like ("Package Settings" link on the right side panel)

Screenshot two shows the image with the permission issue where the "Package Settings" link is missing (and I also cannot push container images to it like I can for the others)

**Screenshot 1**
![Screenshot from 2024-07-08 13-39-23](https://github.com/hyperledger/governance/assets/1583231/28416a03-5a1f-4cd4-ae77-018ed4f0d2e5)

**Screenshot 2**
![Screenshot from 2024-07-08 13-39-12](https://github.com/hyperledger/governance/assets/1583231/99dae8c0-3913-4953-8d1f-366fcc0d18a7)

**Comment by ryjones** [comment]
Hi,
Somehow, the access for that package was not set to sync to repo permissions. I've changed that - please close if access is now correct
Ry

**Comment by petermetz** [comment]
@ryjones It worked, thank you very much!

**Comment by ryjones** [comment]
@petermetz here are three more packages that are not synced:
https://github.com/orgs/hyperledger/packages/container/cactus-corda-4-12-all-in-one-negotiation/settings
https://github.com/orgs/hyperledger/packages/container/cactus-test-npm-registry/settings
https://github.com/orgs/hyperledger/packages/container/cactus-corda-5-all-in-one-solar/settings

**Comment by petermetz** [comment]
> @petermetz here are three more packages that are not synced: https://github.com/orgs/hyperledger/packages/container/cactus-corda-4-12-all-in-one-negotiation/settings https://github.com/orgs/hyperledger/packages/container/cactus-test-npm-registry/settings https://github.com/orgs/hyperledger/packages/container/cactus-corda-5-all-in-one-solar/settings

@ryjones If you could fix the permissions on those as well I'd be very grateful!

I tried to check one of them out manually but GitHub seems to be struggling right now, I'm getting HTTP 500 errors :/

![image](https://github.com/hyperledger/governance/assets/1583231/bbf6e85d-8a83-4822-9eeb-7fa9f2e850e9)

**Comment by ryjones** [comment]
@petermetz done
