### ISSUE TITLE
Add DPulls GitHub Action from Marketplace

### ISSUE THREAD

**Issue by petermetz** [hyperledger/governance#314]
It's free for open source projects according to their pricing page.

https://github.com/marketplace/dpulls

https://www.dpulls.com/

Why though? The old dependency declaration bot that we are currently using in Cacti has broken down and haven't  been maintained in years so we need a new solution that does pretty much the same thing as the old robot, but with it also being maintained.

**Comment by ryjones** [comment]
@petermetz added

**Comment by petermetz** [comment]
@ryjones I was able to set it as a required check in the Cacti upstream repo, thank you!
