### ISSUE TITLE
We need to add our intern to Hyperledger in Github 

### ISSUE THREAD

**Issue by dmitrivenger** [hyperledger/governance#355]
* GitHub ID to add: https://github.com/aoyako
* Project to be added to: hyperledger-iroha

To both teams - 
* https://github.com/orgs/hyperledger-iroha/teams/iroha-maintainers:
* https://github.com/orgs/hyperledger-iroha/teams/iroha-contributors
* Role:
	- Read
	- Triage
	- Write
	- Manage
	- Admin

Thanks 

Dmitri

**Comment by ryjones** [comment]
hi @dmitrivenger - file a PR in hyperledger-iroha/governance
