### ISSUE TITLE
Add tock-ibm to GitHub

### ISSUE THREAD

**Issue by yacovm** [hyperledger/governance#4]
Please include:

* GitHub ID to add: **tock-ibm**
* Project to be added to: **No project, just to the Github org please**.

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams): Fabric contributors

**Comment by ryjones** [comment]
Invite sent!

**Comment by ryjones** [comment]
@yacovm @tock-ibm I se-sent the invite - please visit https://github.com/hyperledger to accept
