### ISSUE TITLE
Grant permissions to fabric-protos-go

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/governance#51]
Please could you grant sufficient permissions so I can add a GitHub deploy key to the `fabric-protos-go` repo. This repo along with `fabric-protos-go-apiv2` are used to publish generated Go modules. `fabric-protos-go-apiv2` already has a deploy key and I would like to update the new GitHub workflows in `fabric-protos` to publish to `fabric-protos-go` in the same way so that the old Azure CI can be removed.

Thanks, James

**Comment by ryjones** [comment]
Done!
