### ISSUE TITLE
Add Ekaterina Semenova, our QA, to GitHub

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/governance#54]
**GitHub ID to add:** @adaagava

**Project to be added to:** 

* https://github.com/hyperledger/iroha
* https://github.com/hyperledger/iroha-java
* https://github.com/hyperledger/iroha-python

**Teams to be added to:**

* https://github.com/orgs/hyperledger/teams/iroha-maintainers
* https://github.com/orgs/hyperledger/teams/iroha-python
* https://github.com/orgs/hyperledger/teams/iroha-java
* https://github.com/orgs/hyperledger/teams/iroha-javascript

**Role:**

	Read / Write

**Comment by ryjones** [comment]
Invite sent!

**Comment by ryjones** [comment]
@6r1d @adaagava has not yet accepted the invite. They need to do so - have them visit github.com/hyperledger to accept
