### ISSUE TITLE
Add Infosys team to GitHub

### ISSUE THREAD

**Issue by arsulegai** [hyperledger/governance#56]
Please include:

* GitHub IDs to add:
  * https://github.com/Arigelas
  * https://github.com/ArchanaArige
  * https://github.com/Anusha-Padmanabhan
* Project to be added to: https://github.com/hyperledger-labs/blockchain-explorer

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams): https://github.com/orgs/hyperledger-labs/teams/blockchain-explorer
* Role:
	- Read
	- Triage
	- Write
	- Manage

**Comment by ryjones** [comment]
Invites sent!
