### ISSUE TITLE
Create a new empty Indy repo: indy-cli-rs

### ISSUE THREAD

**Issue by swcurran** [hyperledger/governance#61]
Please create a new indy repo called indy-cli-rs, which will be the new home for the Indy CLI (Command Line Interface). The CLI is currently in the indy-sdk repo, but we're going to move it out of there, as the new version will not be dependent on the indy-sdk, but instead the Indy Shared components -- indy-vdr and indy-shared-rs. 

If it is possible to somehow move the `cli` folder from the indy-sdk repo into the new repo and preserve the history, that would be nice, but not required.  Worst case, we'll do a PR to the new repo that has a copy of the cli repo with no history.

Maintainers should be the same as for the Indy SDK.

Please let us know if you have any questions.

Thanks!

@WadeBarnes @ashcherbakov

**Comment by ryjones** [comment]
https://github.com/hyperledger/indy-cli-rs
