### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by denyeart** [hyperledger/governance#62]
Please include:

* GitHub ID to add: [SamYuan1990](https://github.com/SamYuan1990)
* Project to be added to: Fabric - fabric-admin-sdk

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/fabric-admin-sdk-maintainers): https://github.com/orgs/hyperledger/teams/fabric-admin-sdk-maintainers
* Role:
	- Manage

**Comment by ryjones** [comment]
invite sent!
