### ISSUE TITLE
Create a new, empty repo: aries-acapy-docs

### ISSUE THREAD

**Issue by swcurran** [hyperledger/governance#65]
Please create a new aries repo called aries-acapy-docs, which will be the new home for Aries Cloud Agent Python documentation that will be published to a gh-pages site using docusaurus.

Maintainers should be the same as for https://github.com/hyperledger/aries-cloudagent-python.

Please let us know if you have any questions.

Thanks!

**Comment by ryjones** [comment]
https://github.com/hyperledger/aries-acapy-docs here you go!
