### ISSUE TITLE
Missing NPM publishing token for fabric-sdk-node

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/governance#68]
* GitHub repo: [fabric-sdk-node](https://github.com/hyperledger/fabric-sdk-node)
* Endpoint: registry.npmjs.org

The GitHub Actions secrets for fabric-sdk-node do not include NPM_TOKEN for publishing NPM packages. Please could you add this organisation secret.

**Comment by ryjones** [comment]
done!

**Comment by bestbeforetoday** [comment]
Thanks, and it works for publishing to NPM from GitHub Actions workflows!
