### ISSUE TITLE
Add Channig to GitHub

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger/governance#69]
Please include:

* GitHub ID to add:  [channingduan](https://github.com/channingduan)
* Project to be added to:  https://github.com/hyperledger/fabric-admin-sdk

One of:

* https://github.com/orgs/hyperledger/teams/fabric-admin-sdk-maintainers
* Role:
      - Admin

ref https://github.com/hyperledger/fabric-admin-sdk/pull/74#pullrequestreview-1239214945

**Comment by ryjones** [comment]
Invite sent!
