### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/governance#7]
Please include:

* GitHub ID to add: https://github.com/QuentinI
* Project to be added to: hyperledger/iroha-python

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams):
* Role:
	- Read
	- Triage
	- Write
	- Manage

**Comment by ryjones** [comment]
Invite sent!
