### ISSUE TITLE
Transfer a repo

### ISSUE THREAD

**Issue by burdettadam** [hyperledger/governance#70]
Please include:

* GitHub repo to transfer: [acapy-wallet-upgrade](https://github.com/andrewwhitehead/acapy-wallet-upgrade)
* Project to be added to: Aries
* Teams with which access:
	* Team name: [aries-cloudagent-python committers](https://github.com/orgs/hyperledger/teams/aries-cloudagent-python-committers)
	* Role:
		- Read
		- Triage
		- Write
		- Manage
		- Admin

**Comment by burdettadam** [comment]
cc @dbluhm @cjhowland

**Comment by ryjones** [comment]
Hi, @burdettadam . Please transfer the repo to my github user, `ryjones`

**Comment by burdettadam** [comment]
Hi @ryjones. In the ACA-Pug meeting today we decided to transfer @andrewwhitehead original project into hyperledger with our fork being merged back into it. @andrewwhitehead Could you assist with the transfer?

**Comment by ryjones** [comment]
@andrewwhitehead howdy - any word?

**Comment by andrewwhitehead** [comment]
I've put in the transfer request

**Comment by ryjones** [comment]
[done!](https://github.com/hyperledger/acapy-wallet-upgrade)
