### ISSUE TITLE
Create a repo

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/governance#78]
Please include:

* GitHub repo to create: bevel-samples
* Project to be added to:  N/A
* Teams with which access:  https://github.com/orgs/hyperledger/teams/bevel-contributors
        * Team name: bevel-samples-committers same as (https://github.com/orgs/hyperledger/teams/bevel-committers)
	* Team name: bevel-samples-admin
	* Role:
		- Admin - (suvajit-sarkar, sowank)

**Comment by ryjones** [comment]
@suvajit-sarkar [here you go!](https://github.com/hyperledger/bevel-samples)
