### ISSUE TITLE
Please Add  @6r1d to Iroha Maintainers Team

### ISSUE THREAD

**Issue by LiraLemur** [hyperledger/governance#8]
Please include:

* GitHub ID to add:  @6r1d
* Project to be added to: HL Iroha

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams): https://github.com/orgs/hyperledger/teams/iroha-maintainers
* Role: the one set by the team rules, please

**Comment by ryjones** [comment]
Invite sent!
