### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/governance#93]
Please include:

* GitHub ID to add: ravikiranjanjanam
* Project to be added to: Hyperledger Bevel

One of:

* [Team to be added to](https://github.com/orgs/hyperledger/teams/0-hyperledger-contributors/teams): https://github.com/orgs/hyperledger/teams/bevel-contributors
* Role: Same as https://github.com/orgs/hyperledger/teams/bevel-committers
	- Read
	- Triage

**Comment by ryjones** [comment]
Hi, @suvajit-sarkar . please updated the `MAINTAINERS.md` files. Once that's done, I'll add him

**Comment by ryjones** [comment]
OK but they aren't on that list :)

**Comment by ryjones** [comment]
Invite sent
