### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by arigelas** [hyperledger/governance#94]
Please include:

* GitHub ID to add: 
https://github.com/saundarya-saurabh
https://github.com/SunnyAjin

* Project to be added to: https://github.com/hyperledger-labs/blockchain-explorer

One of:

* Team to be added to : https://github.com/orgs/hyperledger-labs/teams/blockchain-explorer
* Role:
	- Read
	- Triage
	- Write
	- Manage
	- Admin

**Comment by ryjones** [comment]
Hi,
Please update the [MAINTAINERS.md](https://github.com/hyperledger-labs/blockchain-explorer/blob/main/MAINTAINERS.md) file and I'll add them

**Comment by arigelas** [comment]
Hi Jones, [MAINTAINERS.md](https://github.com/hyperledger-labs/blockchain-explorer/blob/main/MAINTAINERS.md) file updated and PR(https://github.com/hyperledger-labs/blockchain-explorer/pull/366) raised. Please review and do the needful. Thanks

**Comment by ryjones** [comment]
Invites sent!
