### ISSUE TITLE
Create the anoncreds-spec-v2  repo

### ISSUE THREAD

**Issue by swcurran** [hyperledger/governance#96]
Please include:

* GitHub repo to create: anoncreds-spec-v2
* Project to be added to: Hyperledger AnonCreds
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger/teams))
	* Team name: anoncreds-spec-v2-editors
	    * GitHub Id: swcurran, mikelodder, TelegramSam
	    * Role: Maintain
        * Team name: Anoncreds-admin (existing Project Team)
             * Role: Admin

Thanks!

**Comment by ryjones** [comment]
[here you go!](https://github.com/hyperledger/anoncreds-spec-v2)
