### ISSUE TITLE
Create a repo: anoncreds-clsignatures-rs

### ISSUE THREAD

**Issue by swcurran** [hyperledger/governance#99]
Please include:

* GitHub repo to create: anoncreds-clsignatures-rs
* Project to be added to: AnonCreds
* Teams with which access: (examples [on GitHub team list](https://github.com/orgs/hyperledger/teams))
	* Team name: 
	* Role:
		- Read: AnonCreds
		- Triage
		- Write
		- Manage: anoncreds-maintainers
		- Admin: anoncreds-admins

**Comment by ryjones** [comment]
https://github.com/hyperledger/anoncreds-clsignatures-rs here you go!
